ActionController::Routing::Routes.draw do |map|
  map.connect '/sessions/voted',  :controller=>'sessions', :action=>'voted'
  map.connect '/sessions/voting',  :controller=>'sessions', :action=>'voting'
  map.connect '/sessions/update',  :controller=>'sessions', :action=>'update'
  map.connect '/sessions/edit',  :controller=>'sessions', :action=>'edit'
  map.connect '/sessions/destroy',  :controller=>'sessions', :action=>'destroy'
  map.connect '/sessions/log_in',  :controller=>'sessions', :action=>'log_in'
  map.connect '/sessions/logged_in', :controller=>'sessions', :action=>'logged_in'
  map.connect '/sessions/',  :controller=>'sessions', :action=>'home'
  map.connect '/voters/find', :controller=>'voters', :action=>'find'
  map.connect '/voters/:id/delete', :controller=>'voters', :action=>'destroy'
  map.connect '/voters/:id/edit', :controller=>'voters', :action=>'edit'
  map.connect '/voters/:id/update', :controller=>'voters', :action=>'update'
  map.connect '/voters/new',  :controller=>'voters', :action=>'new'
  map.connect '/voters/create', :controller=>'voters', :action=>'create'
  map.connect '/voters/',  :controller=>'voters', :action=>'index'
  map.connect '/candidates/find', :controller=>'candidates', :action=>'find'
  map.connect '/candidates/:id/delete', :controller=>'candidates', :action=>'destroy'
  map.connect '/candidates/:id/edit', :controller=>'candidates', :action=>'edit'
  map.connect '/candidates/:id/update', :controller=>'candidates', :action=>'update'
  map.connect '/candidates/new',  :controller=>'candidates', :action=>'new'
  map.connect '/candidates/create', :controller=>'candidates', :action=>'create'
  map.connect '/candidates/',  :controller=>'candidates', :action=>'index'
  map.connect '/candidates/:id', :controller=>'candidates', :action=>'show'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
